// prompts.js — system + user prompt builders for the full-draft and
// single-section regeneration calls. Anti-fabrication rules are baked into
// the system prompt; sourceless sections are never part of any request.

const ANTI_FABRICATION_RULES = [
  'Never invent clinical detail. Every clinical statement must be traceable to the patient data provided in this request.',
  'If the data for a section is thin or partial, state plainly what the data shows (e.g. "Only vitals are recorded; no physical examination findings are available."). Do not fill gaps with plausible-sounding content.',
  'Use the exact clinical wording recorded in the data for diagnoses, allergies, and medication names; do not reclassify or add qualifiers that are not recorded.',
  'Medication facts belong in medication sections. If a note mentions a medication, use the normalized medications data for medication sections and do not duplicate medication lists in narrative sections.',
  'For sections built from proxy or indirect data, write the useful clinical synthesis first. If a caveat is needed, add at most one short sentence at the end stating that the doctor should verify it. Never use a generic disclaimer as the section content or lead with it.',
  'Output STRICT JSON only: an object keyed by section id, each value a single plain-text string (the full text for that section). Simple hyphen-prefixed lines are allowed for lists; do not use headings, code fences, commentary, or keys beyond the requested section ids.',
].join('\n');

export function buildSystemPrompt() {
  return [
    'You are a clinical documentation assistant generating a draft discharge summary for a hospital doctor.',
    'You only restate and structure data that already exists in the hospital record.',
    'The doctor will review, edit, and approve everything before it becomes part of the record.',
    'Hard rules:',
    ANTI_FABRICATION_RULES,
  ].join('\n\n');
}

function compact(value) {
  return JSON.stringify(value ?? null);
}

function compactComplaintSource(value) {
  const groups = new Map();
  for (const item of Array.isArray(value) ? value : []) {
    const name = String(item?.name ?? '').replace(/\s+/g, ' ').trim();
    if (!name) continue;
    const type = item?.type === 'Associated Complaint' ? 'Associated Complaint' : 'Chief Complaint';
    const key = `${type}\u0000${name.toLocaleLowerCase()}`;
    const group = groups.get(key) || { name, type, recordedDates: [], recordedRemarks: [] };
    if (item?.date && !group.recordedDates.includes(item.date)) group.recordedDates.push(item.date);
    if (item?.remark && !group.recordedRemarks.includes(item.remark)) group.recordedRemarks.push(item.remark);
    groups.set(key, group);
  }
  return [...groups.values()].map((group) => ({
    name: group.name,
    type: group.type,
    recordedDates: group.recordedDates,
    ...(group.recordedRemarks.length ? { recordedRemarks: group.recordedRemarks } : {}),
  }));
}

function sourceValue(source, patientData) {
  return source === 'complaints'
    ? compactComplaintSource(patientData[source])
    : patientData[source] ?? null;
}

// Full-draft request: one JSON object keyed by section id. Only sections with
// a non-null `source` are included; sourceless sections never reach the model.
export function buildDraftUserPrompt(patientData, specialtyConfig) {
  const sections = specialtyConfig.sections.filter((s) => s.source !== null || Array.isArray(s.sources));
  const sourceNames = [...new Set(sections.flatMap((s) => s.sources || [s.source]).filter(Boolean))];
  const sourceData = Object.fromEntries(sourceNames.map((source) => [source, sourceValue(source, patientData)]));
  const sectionSpecs = sections.map((s) => ({
    id: s.id,
    title: s.title,
    promptHint: s.promptHint,
    sources: s.sources || [s.source],
  }));

  return [
    `Generate a draft discharge summary for specialty "${specialtyConfig.label}".`,
    'For each section below, use only the listed source keys from the shared `sourceData` object.',
    'Respond with a single JSON object mapping each requested section id to its text.',
    'Shared sourceData (each source is included once):',
    JSON.stringify(sourceData, null, 2),
    'Sections:',
    JSON.stringify(sectionSpecs, null, 2),
  ].join('\n\n');
}

// Regeneration request: one section's spec + its data, with the current draft
// of all sections as immutable context. The model returns only the new text
// for the target section.
export function buildRegenerateUserPrompt(sectionId, patientData, specialtyConfig, existingDraft) {
  const section = specialtyConfig.sections.find((s) => s.id === sectionId);
  if (!section) throw new Error(`Unknown section id "${sectionId}" for specialty "${specialtyConfig.key}"`);
  if (section.source === null && !Array.isArray(section.sources)) {
    throw new Error(`Section "${sectionId}" has no data source and is never regenerated by the model`);
  }

  return [
    `Regenerate ONLY the "${section.title}" section of the discharge summary (specialty "${specialtyConfig.label}").`,
    'Section spec:',
    JSON.stringify(
      {
        id: section.id,
        title: section.title,
        promptHint: section.promptHint,
        data: (section.sources || [section.source]).reduce((all, source) => ({ ...all, [source]: sourceValue(source, patientData) }), {}),
      },
      null,
      2,
    ),
    'Current draft of all sections (context only — do not change any section other than the target):',
    compact(existingDraft ?? {}),
    'Respond with a single JSON object: { "text": "<new text for this section only>" }.',
  ].join('\n\n');
}
