// prompts.js — system + user prompt builders for the full-draft and
// single-section regeneration calls. Anti-fabrication rules are baked into
// the system prompt; sourceless sections are never part of any request.

const ANTI_FABRICATION_RULES = [
  'Never invent clinical detail. Every clinical statement must be traceable to the patient data provided in this request.',
  'If the data for a section is thin or partial, state plainly what the data shows (e.g. "Only vitals are recorded; no physical examination findings are available."). Do not fill gaps with plausible-sounding content.',
  'Use the exact clinical wording recorded in the data for diagnoses, allergies, and medication names; do not reclassify or add qualifiers that are not recorded.',
  'When a section is a heuristic proxy (History of Present Illness, Past Medical History), flag within the text that it is derived from limited data and requires doctor review.',
  'Output STRICT JSON only: an object keyed by section id, each value a single string (the full text for that section). No markdown, no commentary, no keys beyond the requested section ids.',
].join('\n');

export function buildSystemPrompt() {
  return [
    'You are a clinical documentation assistant generating a draft discharge summary for a hospital doctor.',
    'You only restate and structure data that already exists in the hospital record.',
    'The doctor will review, edit, and approve everything before it becomes part of the record.',
    'Hard rules:',
    ANTI_FABRICATION_RULES,
  ].join('\n\n');
}

function compact(value) {
  return JSON.stringify(value ?? null);
}

// Full-draft request: one JSON object keyed by section id. Only sections with
// a non-null `source` are included; sourceless sections never reach the model.
export function buildDraftUserPrompt(patientData, specialtyConfig) {
  const sections = specialtyConfig.sections.filter((s) => s.source !== null);
  const sectionSpecs = sections.map((s) => ({
    id: s.id,
    title: s.title,
    promptHint: s.promptHint,
    data: patientData[s.source] ?? null,
  }));

  return [
    `Generate a draft discharge summary for specialty "${specialtyConfig.label}".`,
    'For each section below, write the section text from its `data` field only.',
    'Respond with a single JSON object mapping each requested section id to its text.',
    'Sections:',
    JSON.stringify(sectionSpecs, null, 2),
  ].join('\n\n');
}

// Regeneration request: one section's spec + its data, with the current draft
// of all sections as immutable context. The model returns only the new text
// for the target section.
export function buildRegenerateUserPrompt(sectionId, patientData, specialtyConfig, existingDraft) {
  const section = specialtyConfig.sections.find((s) => s.id === sectionId);
  if (!section) throw new Error(`Unknown section id "${sectionId}" for specialty "${specialtyConfig.key}"`);
  if (section.source === null) {
    throw new Error(`Section "${sectionId}" has no data source and is never regenerated by the model`);
  }

  return [
    `Regenerate ONLY the "${section.title}" section of the discharge summary (specialty "${specialtyConfig.label}").`,
    'Section spec:',
    JSON.stringify(
      { id: section.id, title: section.title, promptHint: section.promptHint, data: patientData[section.source] ?? null },
      null,
      2,
    ),
    'Current draft of all sections (context only — do not change any section other than the target):',
    compact(existingDraft ?? {}),
    'Respond with a single JSON object: { "text": "<new text for this section only>" }.',
  ].join('\n\n');
}
